name: Build Project
on:
  push:
    branches: [ master, develop ]
  pull_request:  # 可选：PR 时也触发构建
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 使用最新版 checkout
      - name: Set up JDK 21
        uses: actions/setup-java@v4  # 使用最新版 setup-java
        with:
          java-version: 21
          distribution: 'temurin'  # 推荐 Temurin JDK
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build  # 仅构建，不发布
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4  # 使用 v4 替代弃用的 v3
        with:
          name: build-output
          path: |
            **/build/libs/*.jar  # 上传所有模块的 JAR
            !**/*-sources.jar    # 排除源码 JAR
            !**/*-javadoc.jar    # 排除文档 JAR
